const petsData = [
  { "id": 1, "name": "大耳帽兜", "group": "赛季异色", "image_url": "images/大耳帽兜.png", "price": 60 },
  { "id": 2, "name": "恶魔狼", "group": "赛季异色", "image_url": "images/恶魔狼.png", "price": 35 },
  { "id": 3, "name": "奇丽草", "group": "赛季异色", "image_url": "images/奇丽草.png", "price": 45 },
  { "id": 4, "name": "格兰种子", "group": "赛季异色", "image_url": "images/格兰种子.png", "price": 45 },
  { "id": 5, "name": "拉特", "group": "赛季异色", "image_url": "images/拉特.png", "price": 45 },
  { "id": 6, "name": "治愈兔", "group": "赛季异色", "image_url": "images/治愈兔.png", "price": 60 },
  { "id": 7, "name": "机械方方", "group": "赛季异色", "image_url": "images/机械方方.png", "price": 45 },
  { "id": 8, "name": "呼呼猪", "group": "赛季异色", "image_url": "images/呼呼猪.png", "price": 45 },
  { "id": 9, "name": "柴渣虫", "group": "赛季奇遇异色", "image_url": "images/柴渣虫.png", "price": 65 },
  { "id": 10, "name": "月牙雪熊", "group": "赛季奇遇异色", "image_url": "images/月牙雪熊.png", "price": 35 },
  { "id": 11, "name": "嗜光嗡嗡", "group": "赛季奇遇异色", "image_url": "images/嗜光嗡嗡.png", "price": 65 },
  { "id": 12, "name": "空空颅", "group": "赛季奇遇异色", "image_url": "images/空空颅.png", "price": 60 },
  { "id": 13, "name": "粉粉星", "group": "赛季奇遇异色", "image_url": "images/粉粉星.png", "price": 60 },
  { "id": 14, "name": "贝瑟", "group": "赛季奇遇异色", "image_url": "images/贝瑟.png", "price": 60 },
  { "id": 15, "name": "粉星仔", "group": "赛季奇遇异色", "image_url": "images/粉星仔.png", "price": 60 },
  { "id": 16, "name": "双灯鱼", "group": "赛季奇遇异色", "image_url": "images/双灯鱼.png", "price": 60 },
  { "id": 17, "name": "绒绒", "group": "赛季战令异色", "image_url": "images/绒仙子.png", "price": 70 },
  { "id": 18, "name": "犀角鸟", "group": "赛季战令异色", "image_url": "images/犀角鸟.png", "price": 70 },
  { "id": 19, "name": "火红尾", "group": "活动异色", "image_url": "images/火红尾.png", "price": 60 }
];